# Generated by Django 2.2.19 on 2021-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210813_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
